In [2]:
import os
import pickle
import numpy as np
import pandas as pd

# ===================== 配置你的实际路径 =====================
BASE_DIR = "./data"
DAVIS_LIGANDS = os.path.join(BASE_DIR, "davis/ligands_can.txt")
DAVIS_PROTEINS = os.path.join(BASE_DIR, "davis/proteins.txt")
DAVIS_AFFINITY = os.path.join(BASE_DIR, "davis/Y")

# ===================== 1. 诊断药物文件 =====================
print("======= 🔍 诊断Davis药物文件 (ligands_can.txt) =======")
if os.path.exists(DAVIS_LIGANDS):
    # 读取文件所有内容
    with open(DAVIS_LIGANDS, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]
    
    print(f"文件总行数（非空）：{len(lines)}")
    print(f"前5行内容：")
    for i, line in enumerate(lines[:5]):
        print(f"  第{i+1}行：{line[:100]}...")  # 只显示前100字符
    
    # 尝试解析前5行
    print("\n前5行解析尝试：")
    for i, line in enumerate(lines[:5]):
        import re
        parts = re.split(r'\s+', line, maxsplit=1)
        print(f"  第{i+1}行拆分结果：{len(parts)}个部分 → {parts[:1]}")
else:
    print(f"❌ 药物文件不存在：{DAVIS_LIGANDS}")

# ===================== 2. 诊断靶点文件 =====================
print("\n======= 🔍 诊断Davis靶点文件 (proteins.txt) =======")
if os.path.exists(DAVIS_PROTEINS):
    # 读取文件所有内容
    with open(DAVIS_PROTEINS, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]
    
    print(f"文件总行数（非空）：{len(lines)}")
    print(f"前5行内容：")
    for i, line in enumerate(lines[:5]):
        print(f"  第{i+1}行：{line[:100]}...")
    
    # 尝试解析前5行
    print("\n前5行解析尝试：")
    for i, line in enumerate(lines[:5]):
        import re
        parts = re.split(r'\s+', line, maxsplit=1)
        print(f"  第{i+1}行拆分结果：{len(parts)}个部分 → {parts[:1]}")
else:
    print(f"❌ 靶点文件不存在：{DAVIS_PROTEINS}")

# ===================== 3. 诊断亲和力矩阵 =====================
print("\n======= 🔍 诊断亲和力矩阵 (Y文件) =======")
if os.path.exists(DAVIS_AFFINITY):
    try:
        with open(DAVIS_AFFINITY, "rb") as f:
            affinity_mat = pickle.load(f, encoding="latin1")
        if not isinstance(affinity_mat, np.ndarray):
            affinity_mat = np.array(affinity_mat, dtype=np.float64)
        
        print(f"矩阵类型：{type(affinity_mat)}")
        print(f"矩阵形状：{affinity_mat.shape}")
        print(f"矩阵数据类型：{affinity_mat.dtype}")
        print(f"矩阵数值范围：{np.min(affinity_mat):.4f} ~ {np.max(affinity_mat):.4f}")
        print(f"矩阵前3行前3列：\n{affinity_mat[:3, :3]}")
    except Exception as e:
        print(f"❌ 读取Y文件失败：{e}")
else:
    print(f"❌ Y文件不存在：{DAVIS_AFFINITY}")

# ===================== 4. 诊断TTD文件（可选） =====================
print("\n======= 🔍 诊断TTD文件（可选） =======")
TTD_FILES = {
    "Drug-Disease": os.path.join(BASE_DIR, "TTD/P1-05-Drug_disease.txt"),
    "Target-Sequence": os.path.join(BASE_DIR, "TTD/P2-06-TTD_sequence_all.txt"),
    "Drug-Target": os.path.join(BASE_DIR, "TTD/P1-07-Drug-TargetMapping.xlsx")
}

for name, path in TTD_FILES.items():
    print(f"\n{name} 文件：{path}")
    if os.path.exists(path):
        print(f"  ✅ 文件存在")
        # 简单读取测试
        try:
            if path.endswith(".xlsx"):
                df = pd.read_excel(path, nrows=5)
            else:
                df = pd.read_csv(path, sep="\t", nrows=5, encoding="latin-1", on_bad_lines='skip')
            print(f"  📊 前5行数据形状：{df.shape}")
            print(f"  📋 列名：{list(df.columns)}")
        except Exception as e:
            print(f"  ❌ 读取失败：{e}")
    else:
        print(f"  ❌ 文件不存在")

print("\n======= 📝 诊断完成 =======")

======= 🔍 诊断Davis药物文件 (ligands_can.txt) =======
文件总行数（非空）：1
前5行内容：
  第1行：{"11314340": "CC1=C2C=C(C=CC2=NN1)C3=CC(=CN=C3)OCC(CC4=CC=CC=C4)N", "24889392": "CC(C)(C)C1=CC(=NO1)...

前5行解析尝试：
  第1行拆分结果：2个部分 → ['{"11314340":']

======= 🔍 诊断Davis靶点文件 (proteins.txt) =======
文件总行数（非空）：1
前5行内容：
  第1行：{"AAK1": "MKKFFDSRREQGGSGLGSGSSGGGGSTSGLGSGYIGRVFGIGRQQVTVDEVLAEGGFAIVFLVRTSNGMKCALKRMFVNNEHDLQVCKRE...

前5行解析尝试：
  第1行拆分结果：2个部分 → ['{"AAK1":']

======= 🔍 诊断亲和力矩阵 (Y文件) =======
矩阵类型：<class 'numpy.ndarray'>
矩阵形状：(68, 442)
矩阵数据类型：float64
矩阵数值范围：0.0160 ~ 10000.0000
矩阵前3行前3列：
[[4.3e+01 1.0e+04 1.0e+04]
 [1.0e+04 1.0e+04 1.0e+04]
 [1.0e+04 7.5e+01 1.9e+00]]

======= 🔍 诊断TTD文件（可选） =======

Drug-Disease 文件：./data/TTD/P1-05-Drug_disease.txt
  ✅ 文件存在
  📊 前5行数据形状：(5, 1)
  📋 列名：['TTD - Therapeutic Targets Database Full Data Download File']

Target-Sequence 文件：./data/TTD/P2-06-TTD_sequence_all.txt
  ✅ 文件存在
  📊 前5行数据形状：(5, 1)
  📋 列名：['TTD - Therapeutic Targets Database Full Data Download File']

Drug-Target 文件：.

In [ ]:
import pandas as pd

# 替换为你的训练特征文件路径
TRAIN_FEATURE_PATH = "../data_preprocessing/dta/davis/log_and_file/dta_features.csv"

# 读取前1行，查看所有列名
df = pd.read_csv(TRAIN_FEATURE_PATH, nrows=1)
print("训练特征文件的所有列名：")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# 查找可能的ID列（常见命名：drug_id/protein_id/target_id/drug_id_xxx等）
id_like_cols = [col for col in df.columns if any(key in col.lower() for key in ["drug", "target", "protein", "id"])]
print(f"\n疑似ID列：{id_like_cols}")

In [7]:
import pandas as pd
import numpy as np
from scipy import stats

# 加载你上传的预测结果
df = pd.read_csv("./mtc_prediction_results/mtc_dta_dti_predictions.csv")

# 筛选MTC核心靶点
mtc_genes = ["RET", "MET"]
df_mtc = df[df["target_gene"].isin(mtc_genes)].copy()

# 直接计算真实亲和力（nM）与模型pred_affinity的相关性
corr_all, p_all = stats.pearsonr(df_mtc["true_affinity"], df_mtc["pred_affinity"])
print(f"真实亲和力（nM）与pred_affinity的相关系数：r = {corr_all:.4f}, p = {p_all:.6f}")

# 按靶点分开算
for gene in mtc_genes:
    gene_df = df_mtc[df_mtc["target_gene"] == gene]
    corr_gene, p_gene = stats.pearsonr(gene_df["true_affinity"], gene_df["pred_affinity"])
    print(f"{gene}靶点：r = {corr_gene:.4f}, p = {p_gene:.6f}")

真实亲和力（nM）与pred_affinity的相关系数：r = 0.0550, p = 0.231424
RET靶点：r = 0.0375, p = 0.538121
MET靶点：r = 0.2201, p = 0.001557
